image: ubuntu:18.04
cache:
  paths:
  - .stack/
  - .stack-work/

build:
  stage: build
  script:
  - source scripts/ci.sh
  - prebuild
  - build
  artifacts:
    paths:
    - build.tar.gz

deploy:
  stage: deploy
  dependencies:
  - build
  only:
  - staging
  - master
  script:
  - source scripts/ci.sh
  - deploy $CI_COMMIT_REF_NAME
