resolver: lts-13.18

packages:
- haskellgames.com
- games/helicopter
- games/snake

extra-deps:
- git: https://github.com/schell/milkshake.git
  commit: 5dc89f5043b5f7f5f5b3faee72fb1679e6cf3236
- git: https://github.com/schell/audaxian-toolbox.git
  commit: e0ecd323229f3803a348cfae5e6530dbb7944f72
- reactive-banana-1.2.1.0
