name:                haskell-games-snake
version:             0.1.0.0
github:              "githubuser/haskell-games-snake"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "efsubenovex@gmail.com"
copyright:           "2018 Schell Scivally"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/schell/haskell-games-snake#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wnoncanonical-monadfail-instances
  - -Wredundant-constraints

executables:
  haskell-games-snake-exe:
    main:                Main.lhs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base       >= 4.7 && < 5
    - containers
    - lens
    - linear
    - markdown-unlit
    - mtl
    - pretty-show
    - random
    - sdl2       >= 2.4.1.0
    - time
    - transformers
